/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppTodo {
    }
}
declare global {
    interface HTMLAppTodoElement extends Components.AppTodo, HTMLStencilElement {
    }
    var HTMLAppTodoElement: {
        prototype: HTMLAppTodoElement;
        new (): HTMLAppTodoElement;
    };
    interface HTMLElementTagNameMap {
        "app-todo": HTMLAppTodoElement;
    }
}
declare namespace LocalJSX {
    interface AppTodo {
    }
    interface IntrinsicElements {
        "app-todo": AppTodo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-todo": LocalJSX.AppTodo & JSXBase.HTMLAttributes<HTMLAppTodoElement>;
        }
    }
}
